print("Hi", "Venkata", "Dhruva")
print("Hi", "Venkata", "Dhruva")
print("Hi", "Venkata", "Dhruva", end='')
print("Hi", "Venkata", "Dhruva")
print("Hi", "Venkata", "Dhruva", end='-')
print("Hi", "Venkata", "Dhruva")
print("Hi", "Venkata", "Dhruva", end='\t')
print("Hi", "Venkata", "Dhruva")
print("Hi", "Venkata", "Dhruva", sep='-', end='\t')
print("Hi", "Venkata", "Dhruva")
