name = "This is a big line"
print(name)
print(len(name))
print(type(name))
print(name[14])
print(name[-1])
print(name[-2])
print(name[-3])
print(name[-4])
print(name[-5])
print(name[-12])
print(name[-11])
print(name[-10])
print(name[-9])
print(name[-8])
print(name[-7])
print(name[-6])
print(name[-15])
print(name[-14])
print(name[-13])
print(name[-17])
print(name[-16])

