num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
result = num1+num2
print(result)
num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
result = int(num1)+int(num2)
print(result)
s = input('---> ')
print(s)
